name: posts_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  flutter_lints: ^2.0.0
  equatable: ^2.0.3
  internet_connection_checker: ^0.0.1+4
  dio: ^4.0.6
  get_it: ^7.2.0
  pretty_dio_logger: ^1.1.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true