// Mocks generated by Mockito 5.2.0 from annotations
// in posts_app/test/data/data_sources/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:posts_app/data/core/dio_helper.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DioHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioHelper extends _i1.Mock implements _i2.DioHelper {
  MockDioHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> request(
          {String? endpoint,
          _i2.Method? method,
          Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
          Invocation.method(#request, [],
              {#endpoint: endpoint, #method: method, #params: params}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
